"use client";

import { useMemo, useState } from "react";
import styles from "./amortizacao.module.css";

type SystemType = "sac" | "price";
type Strategy = "term" | "payment";
type ScheduleRow = { month:number; openingBalance:number; interest:number; amortization:number; payment:number; closingBalance:number; extraApplied?:number };

const money = new Intl.NumberFormat("pt-BR", { style:"currency", currency:"BRL", maximumFractionDigits:0 });
const rowsPerPage = 12;
function monthlyRateFromAnnual(p:number){const a=Math.max(p,0)/100;return a===0?0:Math.pow(1+a,1/12)-1}
function pricePayment(b:number,m:number,r:number){if(b<=0||m<=0)return 0;if(r===0)return b/m;return(b*r)/(1-Math.pow(1+r,-m))}
function buildStandardSchedule(balance:number,months:number,rate:number,system:SystemType){const s:ScheduleRow[]=[];if(balance<=0||months<=0)return s;let c=balance;if(system==="price"){const fixed=pricePayment(balance,months,rate);for(let month=1;month<=months&&c>.005;month++){const opening=c,interest=opening*rate,amortization=month===months?opening:Math.min(Math.max(fixed-interest,0),opening),payment=interest+amortization;c=Math.max(opening-amortization,0);s.push({month,openingBalance:opening,interest,amortization,payment,closingBalance:c})}return s}const constant=balance/months;for(let month=1;month<=months&&c>.005;month++){const opening=c,interest=opening*rate,amortization=month===months?opening:Math.min(constant,opening),payment=interest+amortization;c=Math.max(opening-amortization,0);s.push({month,openingBalance:opening,interest,amortization,payment,closingBalance:c})}return s}
function buildReducedTermSchedule(original:number,newBalance:number,months:number,rate:number,system:SystemType){const s:ScheduleRow[]=[];if(newBalance<=0)return s;let c=newBalance;if(system==="price"){const originalPayment=pricePayment(original,months,rate);for(let month=1;month<=months&&c>.005;month++){const opening=c,interest=opening*rate,amortization=Math.min(Math.max(originalPayment-interest,0),opening),payment=interest+amortization;c=Math.max(opening-amortization,0);s.push({month,openingBalance:opening,interest,amortization,payment,closingBalance:c});if(amortization<=0)break}return s}const originalAmortization=original/months;for(let month=1;month<=months&&c>.005;month++){const opening=c,interest=opening*rate,amortization=Math.min(originalAmortization,opening),payment=interest+amortization;c=Math.max(opening-amortization,0);s.push({month,openingBalance:opening,interest,amortization,payment,closingBalance:c})}return s}
function buildAnnualSchedule(balance:number,months:number,rate:number,system:SystemType,strategy:Strategy,annualExtra:number,firstMonth:number){const s:ScheduleRow[]=[];if(balance<=0)return s;let c=balance;const originalPayment=pricePayment(balance,months,rate),originalAmortization=balance/months;for(let month=1;month<=months&&c>.005;month++){const opening=c,interest=opening*rate;let amortization:number;if(strategy==="payment"){const remaining=Math.max(months-month+1,1);amortization=system==="price"?Math.min(Math.max(pricePayment(opening,remaining,rate)-interest,0),opening):Math.min(opening/remaining,opening)}else{amortization=system==="price"?Math.min(Math.max(originalPayment-interest,0),opening):Math.min(originalAmortization,opening)}const payment=interest+amortization;let closing=Math.max(opening-amortization,0);let extraApplied=0;if(annualExtra>0&&month>=firstMonth&&(month-firstMonth)%12===0&&closing>0){extraApplied=Math.min(annualExtra,closing);closing-=extraApplied}s.push({month,openingBalance:opening,interest,amortization,payment,closingBalance:closing,extraApplied});c=closing}return s}
function totalInterest(s:ScheduleRow[]){return s.reduce((a,r)=>a+r.interest,0)}
function totalExtra(s:ScheduleRow[]){return s.reduce((a,r)=>a+(r.extraApplied??0),0)}
function formatDuration(months:number){if(months<=0)return"Sem redução de prazo";const y=Math.floor(months/12),m=months%12;if(y===0)return`${m} ${m===1?"mês":"meses"}`;if(m===0)return`${y} ${y===1?"ano":"anos"}`;return`${y} ${y===1?"ano":"anos"} e ${m} ${m===1?"mês":"meses"}`}

export function AmortizationSimulator(){
 const[balance,setBalance]=useState(250000),[remainingMonths,setRemainingMonths]=useState(300),[annualRate,setAnnualRate]=useState(10),[system,setSystem]=useState<SystemType>("sac"),[strategy,setStrategy]=useState<Strategy>("term"),[extraPayment,setExtraPayment]=useState(30000),[annualEnabled,setAnnualEnabled]=useState(false),[annualExtra,setAnnualExtra]=useState(10000),[firstAnnualMonth,setFirstAnnualMonth]=useState(12),[tablePage,setTablePage]=useState(0);
 const result=useMemo(()=>{const safeBalance=Math.max(balance,0),safeMonths=Math.max(Math.round(remainingMonths),1),rate=monthlyRateFromAnnual(annualRate),extra=Math.min(Math.max(extraPayment,0),safeBalance),newBalance=Math.max(safeBalance-extra,0),baseline=buildStandardSchedule(safeBalance,safeMonths,rate,system);const after=annualEnabled?buildAnnualSchedule(newBalance,safeMonths,rate,system,strategy,Math.max(annualExtra,0),Math.max(Math.min(Math.round(firstAnnualMonth),safeMonths),1)):(strategy==="term"?buildReducedTermSchedule(safeBalance,newBalance,safeMonths,rate,system):buildStandardSchedule(newBalance,safeMonths,rate,system));const baselineInterest=totalInterest(baseline),afterInterest=totalInterest(after),baselineFirstPayment=baseline[0]?.payment??0,afterFirstPayment=after[0]?.payment??0;return{safeBalance,safeMonths,extra,newBalance,baseline,after,baselineInterest,afterInterest,savedInterest:Math.max(baselineInterest-afterInterest,0),monthsSaved:Math.max(baseline.length-after.length,0),baselineFirstPayment,afterFirstPayment,paymentReduction:Math.max(baselineFirstPayment-afterFirstPayment,0),annualTotal:totalExtra(after)}} ,[balance,remainingMonths,annualRate,system,strategy,extraPayment,annualEnabled,annualExtra,firstAnnualMonth]);
 const sliderMax=Math.max(Math.round(result.safeBalance/1000)*1000,1000),pageCount=Math.max(Math.ceil(result.baseline.length/rowsPerPage),1),safePage=Math.min(tablePage,pageCount-1),start=safePage*rowsPerPage,baselineRows=result.baseline.slice(start,start+rowsPerPage);
 return <section className={styles.simulatorSection}><div className={`container ${styles.simulatorGrid}`}><div className={styles.controlsCard}><div className={styles.cardHeading}><span>Seu financiamento hoje</span><h2>Monte o cenário atual.</h2></div>
 <div className={styles.fieldGrid}><label className={styles.field}><span>Saldo devedor atual</span><div className={styles.inputShell}><span>R$</span><input type="number" min="0" step="1000" value={balance} onChange={e=>setBalance(Number(e.target.value))}/></div></label><label className={styles.field}><span>Prazo restante</span><div className={styles.inputShell}><input type="number" min="1" max="420" value={remainingMonths} onChange={e=>setRemainingMonths(Math.max(Number(e.target.value),1))}/><span>meses</span></div></label><label className={styles.field}><span>Taxa anual</span><div className={styles.inputShell}><input type="number" min="0" max="30" step="0.01" value={annualRate} onChange={e=>setAnnualRate(Math.max(Number(e.target.value),0))}/><span>% a.a.</span></div></label></div>
 <fieldset className={styles.optionFieldset}><legend>Sistema de amortização</legend><div className={styles.optionGrid}><label className={system==="sac"?styles.activeOption:""}><input type="radio" checked={system==="sac"} onChange={()=>setSystem("sac")}/><span><strong>SAC</strong><small>Parcelas decrescentes</small></span></label><label className={system==="price"?styles.activeOption:""}><input type="radio" checked={system==="price"} onChange={()=>setSystem("price")}/><span><strong>Price</strong><small>Parcela calculada constante</small></span></label></div></fieldset>
 <div className={styles.aportBlock}><div className={styles.aportHeading}><div><span>Aporte extraordinário hoje</span><strong>{money.format(result.extra)}</strong></div><label><span>Digitar valor</span><input type="number" min="0" max={result.safeBalance} step="1000" value={extraPayment} onChange={e=>setExtraPayment(Math.min(Math.max(Number(e.target.value),0),result.safeBalance))}/></label></div><input className={styles.range} type="range" min="0" max={sliderMax} step="1000" value={Math.min(result.extra,sliderMax)} onChange={e=>setExtraPayment(Number(e.target.value))}/><div className={styles.rangeLabels}><span>R$ 0</span><span>{money.format(sliderMax)}</span></div></div>
 <div className={styles.annualBlock}><div className={styles.annualTitle}><div><span>Aporte anual</span><strong>Simule FGTS, 13º, bônus ou outra reserva anual.</strong></div><label className={styles.switchLabel}><input type="checkbox" checked={annualEnabled} onChange={e=>{setAnnualEnabled(e.target.checked);setTablePage(0)}}/><span>{annualEnabled?"Ativado":"Ativar"}</span></label></div>{annualEnabled&&<><div className={styles.annualFields}><label className={styles.field}><span>Valor por ano</span><div className={styles.inputShell}><span>R$</span><input type="number" min="0" step="1000" value={annualExtra} onChange={e=>setAnnualExtra(Math.max(Number(e.target.value),0))}/></div></label><label className={styles.field}><span>Primeiro aporte</span><div className={styles.inputShell}><input type="number" min="1" max={result.safeMonths} value={firstAnnualMonth} onChange={e=>setFirstAnnualMonth(Math.max(Number(e.target.value),1))}/><span>mês</span></div></label></div><p>O valor é aplicado a cada 12 meses a partir do mês escolhido. Se usar FGTS, confirme antes as regras e a disponibilidade do saldo.</p><a href="/guias/fgts">Entender como usar o FGTS</a></>}</div>
 <fieldset className={styles.optionFieldset}><legend>O que você quer reduzir?</legend><div className={styles.optionGrid}><label className={strategy==="term"?styles.activeOption:""}><input type="radio" checked={strategy==="term"} onChange={()=>{setStrategy("term");setTablePage(0)}}/><span><strong>Reduzir prazo</strong><small>Terminar antes</small></span></label><label className={strategy==="payment"?styles.activeOption:""}><input type="radio" checked={strategy==="payment"} onChange={()=>{setStrategy("payment");setTablePage(0)}}/><span><strong>Reduzir parcela</strong><small>Manter o prazo de referência</small></span></label></div></fieldset></div>
 <aside className={styles.resultsCard} aria-live="polite"><div className={styles.resultHeadline}><span>Impacto estimado dos aportes</span><strong>{strategy==="term"?formatDuration(result.monthsSaved):money.format(result.paymentReduction)}</strong><p>{strategy==="term"?"de financiamento a menos":"de redução estimada na primeira parcela"}</p></div><div className={styles.metricsGrid}><div><span>Saldo após aporte inicial</span><strong>{money.format(result.newBalance)}</strong></div><div><span>Juros economizados</span><strong>{money.format(result.savedInterest)}</strong></div><div><span>Novo prazo</span><strong>{result.after.length} meses</strong></div><div><span>Aportes anuais aplicados</span><strong>{money.format(result.annualTotal)}</strong></div></div><div className={styles.timelineCompare}><div><div><span>Sem aportes</span><strong>{result.baseline.length} meses</strong></div><div className={styles.timelineTrack}><span style={{width:"100%"}}/></div></div><div><div><span>Com estratégia</span><strong>{result.after.length} meses</strong></div><div className={styles.timelineTrack}><span className={styles.afterBar} style={{width:`${result.baseline.length?Math.max(result.after.length/result.baseline.length*100,2):0}%`}}/></div></div></div><dl className={styles.resultList}><div><dt>Juros futuros sem aportes</dt><dd>{money.format(result.baselineInterest)}</dd></div><div><dt>Juros futuros com estratégia</dt><dd>{money.format(result.afterInterest)}</dd></div><div><dt>Primeira parcela sem aportes</dt><dd>{money.format(result.baselineFirstPayment)}</dd></div><div><dt>Aporte aplicado hoje</dt><dd>{money.format(result.extra)}</dd></div></dl></aside></div>
 <div className={`container ${styles.tableSection}`}><div className={styles.tableHeading}><div><span>Comparação mês a mês</span><h2>Veja o saldo antes e depois dos aportes.</h2></div><strong>{system.toUpperCase()} · {strategy==="term"?"redução de prazo":"redução de parcela"}</strong></div><div className={styles.tableCard}><div className={styles.tableScroll}><table><thead><tr><th>Mês</th><th>Saldo sem aportes</th><th>Saldo com estratégia</th><th>Parcela base</th><th>Parcela simulada</th><th>Aporte anual</th></tr></thead><tbody>{baselineRows.map((row,index)=>{const a=result.after[start+index];return <tr key={row.month}><td><strong>{row.month}</strong></td><td>{money.format(row.closingBalance)}</td><td>{money.format(a?.closingBalance??0)}</td><td>{money.format(row.payment)}</td><td>{money.format(a?.payment??0)}</td><td>{money.format(a?.extraApplied??0)}</td></tr>})}</tbody></table></div><div className={styles.pagination}><button disabled={safePage===0} onClick={()=>setTablePage(p=>Math.max(p-1,0))}>12 meses anteriores</button><span>Página {safePage+1} de {pageCount}</span><button disabled={safePage>=pageCount-1} onClick={()=>setTablePage(p=>Math.min(p+1,pageCount-1))}>Próximos 12 meses</button></div></div></div></section>
}
